-- -------------------------------------------------------------
-- CRIAÇÃO DO BANCO DE DADOS
-- -------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS DB_SUPERMERCADO DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE DB_SUPERMERCADO;

-- -------------------------------------------------------------
-- TABELAS DE ENDEREÇO (Estrutura 3FN)
-- -------------------------------------------------------------
CREATE TABLE TB_ESTADO (
    ID_ESTADO INT AUTO_INCREMENT,
    SG_UF CHAR(2) NOT NULL,
    NM_ESTADO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UN_SG_UF UNIQUE (SG_UF)
);

CREATE TABLE TB_CIDADE (
    ID_CIDADE INT AUTO_INCREMENT,
    NM_CIDADE VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE),
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE TABLE TB_LOGRADOURO (
    ID_LOGRADOURO INT AUTO_INCREMENT,
    CD_CEP CHAR(8) NOT NULL,
    NM_LOGRADOURO VARCHAR(150) NOT NULL,
    NM_BAIRRO VARCHAR(100) NOT NULL,
    ID_CIDADE INT NOT NULL,
    CONSTRAINT PK_LOGRADOURO PRIMARY KEY (ID_LOGRADOURO),
    CONSTRAINT FK_LOGRADOURO_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES TB_CIDADE(ID_CIDADE)
);

-- Índice não-único para otimização de buscas por CEP
CREATE INDEX IX_LOGRADOURO_CEP ON TB_LOGRADOURO (CD_CEP);

CREATE TABLE TB_LOCALIDADE (
    ID_LOCALIDADE INT AUTO_INCREMENT,
    ID_LOGRADOURO INT NOT NULL,
    TX_NUMERO VARCHAR(20) NOT NULL,
    TX_COMPLEMENTO VARCHAR(100),
    CONSTRAINT PK_LOCALIDADE PRIMARY KEY (ID_LOCALIDADE),
    CONSTRAINT FK_LOCALIDADE_LOGRADOURO FOREIGN KEY (ID_LOGRADOURO) REFERENCES TB_LOGRADOURO(ID_LOGRADOURO)
);

-- -------------------------------------------------------------
-- TABELAS DE CLIENTE E CONTATO
-- -------------------------------------------------------------
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT,
    NM_CLIENTE VARCHAR(150) NOT NULL,
    CD_CPF CHAR(11) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    ID_LOCALIDADE INT NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UN_CLIENTE_CPF UNIQUE (CD_CPF),
    CONSTRAINT FK_CLIENTE_LOCALIDADE FOREIGN KEY (ID_LOCALIDADE) REFERENCES TB_LOCALIDADE(ID_LOCALIDADE)
);

-- Criação de Tabela de Domínio de Tipos de Contato (TB_TIPO_CONTATO_CLIENTE)

CREATE TABLE TB_TIPO_CONTATO_CLIENTE (
    ID_TIPO_CONTATO CHAR(1) NOT NULL,
    TX_TIPO_CONTATO VARCHAR(20) NOT NULL, -- 'TELEFONE', 'EMAIL', ETC
    CONSTRAINT PK_TIPO_CONTATO_CLIENTE PRIMARY KEY (ID_TIPO_CONTATO)
);

CREATE TABLE TB_CONTATO_CLIENTE (
    ID_CONTATO INT AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_TIPO_CONTATO CHAR(1) NOT NULL, 
    TX_CONTATO VARCHAR(100) NOT NULL,
    ST_WHATSAPP CHAR(1) DEFAULT 'N', -- 'S' ou 'N'
    CONSTRAINT PK_CONTATO_CLIENTE PRIMARY KEY (ID_CONTATO),
    CONSTRAINT FK_CONTATO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_TIPO_CONTATO_CLIENTE FOREIGN KEY (ID_TIPO_CONTATO) REFERENCES TB_TIPO_CONTATO_CLIENTE(ID_TIPO_CONTATO),
    CONSTRAINT CK_ST_WHATSAPP CHECK (ST_WHATSAPP IN ('S', 'N'))
);

-- -------------------------------------------------------------
-- TABELAS DE PRODUTO E CATEGORIA
-- -------------------------------------------------------------
CREATE TABLE TB_CATEGORIA_PRODUTO (
    ID_CATEGORIA_PRODUTO INT AUTO_INCREMENT,
    NM_CATEGORIA_PRODUTO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CATEGORIA_PRODUTO PRIMARY KEY (ID_CATEGORIA_PRODUTO)
);

CREATE TABLE TB_PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT,
    NM_PRODUTO VARCHAR(150) NOT NULL,
    VL_PRECO DECIMAL(12,3) NOT NULL, -- Precisão de 3 casas decimais
    ID_CATEGORIA_PRODUTO INT NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO),
    CONSTRAINT FK_PRODUTO_CATEG_PROD FOREIGN KEY (ID_CATEGORIA_PRODUTO) REFERENCES TB_CATEGORIA_PRODUTO(ID_CATEGORIA_PRODUTO)
);

-- -------------------------------------------------------------
-- TABELAS DE PEDIDO E ITENS
-- -------------------------------------------------------------

-- Criação de Tabela de Domínio de Situações de Pedidos (TB_SITUACAO_PEDIDO)

CREATE TABLE TB_SITUACAO_PEDIDO (
    ID_SITUACAO CHAR(1) NOT NULL,
    TX_SITUACAO_PEDIDO VARCHAR(30) NOT NULL, -- 'Concluído', 'Em Processamento', 'Em Pagamento', 'Cancelado'
    CONSTRAINT PK_SITUACAO_PEDIDO PRIMARY KEY (ID_SITUACAO)
);

CREATE TABLE TB_PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    DT_PEDIDO DATETIME NOT NULL,
    VL_TOTAL DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    ID_SITUACAO_PEDIDO CHAR(1) NOT NULL, 
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_SITUACAO_PEDIDO FOREIGN KEY (ID_SITUACAO_PEDIDO) REFERENCES TB_SITUACAO_PEDIDO(ID_SITUACAO)
);

CREATE TABLE TB_ITEM_PEDIDO (
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QT_PRODUTO DECIMAL(10,3) NOT NULL,
    VL_UNITARIO DECIMAL(12,3) NOT NULL,
    CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY (ID_PEDIDO, ID_PRODUTO),
    CONSTRAINT FK_ITEM_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_ITEM_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO)
);

-- Adições, por conta da Parte 3 do Desafio

-- Índice composto de cobertura, focado na filtragem e ordenação da consulta
CREATE INDEX IX_PEDIDO_SITUACAO_VALOR_DATA 
    ON TB_PEDIDO (id_situacao_pedido, vl_total, dt_pedido, id_cliente);

CREATE UNIQUE INDEX UN_TX_SITUACAO ON TB_SITUACAO_PEDIDO (TX_SITUACAO_PEDIDO);

CREATE UNIQUE INDEX UN_ID_CLIENTE ON TB_CLIENTE (NM_CLIENTE, CD_CPF);
